# Much of this comes from https://dev.to/marrouchi/the-challenge-about-ssl-in-docker-containers-no-one-talks-about-32gh

x-common:
  TIMEZONE: &timezone "${TZ}"

x-services:
  CERTBOT_CONFIG: &certbot_config 
    image: ghcr.io/anarchobooleanism/certbot-dns-namecheap:latest@sha256:d3a16d263a30987cac55ad50f8ed9cf65c1649c913b26827e8e1f05dffdc386d

services:
  nginx:
    image: ghcr.io/anarchobooleanism/saphnet-nginx:v0.6.0@sha256:72d76a4c0afcba01c7388cc558f4ea2b9669d37a6d9d30fb5c03948adb028f6b
    depends_on:
      bootstrap:
        condition: service_completed_successfully
    volumes:
      # Main conf file
      - ${NGINX_PROXIES_FILE}:/etc/nginx/proxies.conf:ro
      # Certificate files
      - certbot-conf:/etc/letsencrypt:ro
    environment:
      TZ: *timezone
    ports:
      - "80:80"
      - "443:443"
    networks: # For connecting with other services directly
      - central-network
    restart: unless-stopped
  
  certbot:
    depends_on:
      bootstrap:
        condition: service_completed_successfully
    volumes:
      - certbot-conf:/etc/letsencrypt
      - ${NAMECHEAP_API_DETAILS_FILE}:/namecheap.ini
    environment:
      TZ: *timezone
    # Renew certificates every 12 hours
    entrypoint: |
      /bin/sh -c 'trap exit TERM; while :; do certbot renew -vv; sleep 12h & wait $${!}; done;'
    <<: *certbot_config

  bootstrap:
    volumes:
      - certbot-conf:/etc/letsencrypt
      - ${NAMECHEAP_API_DETAILS_FILE}:/namecheap.ini
    environment:
      TZ: *timezone
      CERTBOT_EMAIL: "${CERTBOT_EMAIL}"
      CERTBOT_DOMAINS: "${CERTBOT_DOMAINS}"
    # Renew certificates every 12 hours
    entrypoint:
      - /bin/sh
      - -c
      - |
        if [ -e /etc/letsencrypt/reverse-proxy-bootstrap-complete ]; then
          echo "It appears that the reverse proxy bootstrapping process is completed. Exiting..."
          exit 0
        else
          echo "The reverse proxy bootstrapping process has not been started before. Starting now!"
        fi

        certonly -a dns-namecheap \
          --dns-namecheap-credentials=/namecheap.ini \
          --agree-tos --non-interactive -vv \
          --no-eff-email \
          --email "$$CERTBOT_EMAIL" \
          --domains "$$CERTBOT_DOMAINS"
        
        echo "Process completed, so we're marking this job as done..."
        touch /etc/letsencrypt/reverse-proxy-bootstrap-complete
    <<: *certbot_config

networks:
  central-network:
    name: central-network
    external: true

volumes:
  certbot-conf:
    name: certbot-conf
