# instance-values.toml
# A list of values to use to instantiate docker-host for docker-host-core

hostname = "docker-host-core"
domain = "int-net.saphnet.xyz"

cicd-authorized-keys = [
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIC03O18a2GH5euD1k5mKW67mC04m1GyvmgymxOqrCypH saphnet-ansible-playbook", # To remove
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHRbMBsGPMgxsbmc9jVUzuFG6OoYLj5Mj1z/g2N3PbDi saphnet-ansible-playbook", # ansible: 2026-06-29
]

[networking]
ip-address = "192.168.8.202" # docker-host-core.int-net.saphnet.xyz
ip-prefix-length = 23 # 192.168.8.0/23
interface = "ens18"
