################################
# 🦎 KOMODO COMPOSE - MONGO 🦎 #
################################

## This compose file will deploy:
##   1. MongoDB
##   2. Komodo Core
##   3. Komodo Periphery

services:
  mongo:
    image: mongo:8@sha256:7abfba0d07c9330373f8173981ea4d09cd8a82cdf0e86ccaf7008848d1d24f62
    labels:
      komodo.skip: # Prevent Komodo from stopping with StopAllContainers
    command: --quiet --wiredTigerCacheSizeGB 0.25
    # ports:
    #   - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${KOMODO_DB_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${KOMODO_DB_PASSWORD}"
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb
    networks:
      - komodo-network
    restart: unless-stopped
  
  core:
    image: ghcr.io/moghtech/komodo-core:2.1.2@sha256:8a7dbba232e4e49797bb412be5f78207c89fcf22cc2727b38631ae30f7518a4c
    container_name: komodo-core
    init: true
    depends_on:
      - mongo
    labels:
      komodo.skip: # Prevent Komodo from stopping with StopAllContainers
    ports:
      - "9120:9120"
    env_file: "${ENV_FILE}"
    environment:
      KOMODO_DATABASE_ADDRESS: mongo:27017
      KOMODO_DATABASE_USERNAME: "${KOMODO_DB_USERNAME}"
      KOMODO_DATABASE_PASSWORD: "${KOMODO_DB_PASSWORD}"
      # Key file for SOPS, to use in sops commands
      SOPS_AGE_KEY_FILE: "/root/.config/sops/age/keys.txt"
      # More custom vars
      GIT_ACCESS_TOKEN: "${GIT_ACCESS_TOKEN}"
      DOCKER_ACCESS_TOKEN: "${DOCKER_ACCESS_TOKEN}"
    volumes:
      - komodo-keys:/config/keys
      ## Store dated backups of the database - https://komo.do/docs/setup/backup
      - ${COMPOSE_KOMODO_BACKUPS_PATH}:/backups
      ## Store sync files on server
      # - /path/to/syncs:/syncs
      ## Optionally mount a custom core.config.toml
      - ${KOMODO_CONFIG_PATH}:/config/config.toml
      # SOPS key
      - ${KOMODO_SOPS_KEY_PATH}:/root/.config/sops/age/keys.txt:ro
    ## Allows for systemd Periphery connection at 
    ## "https://host.docker.internal:8120"
    # extra_hosts:
    #   - host.docker.internal:host-gateway
    networks: # For connecting with other services directly
      - komodo-network
      - central-network
    restart: unless-stopped

  ## Deploy Periphery container using this block,
  ## or deploy the Periphery binary with systemd using 
  ## https://github.com/moghtech/komodo/tree/main/scripts
  periphery:
    image: ghcr.io/nikhil-gohil/komodo-periphery-sops:v2.1.2@sha256:a7849539864080708afc9a59dfd377f159a289cf621e7fe75c6c67ee16e020c0 # Temporary for now until Komodo adds SOPS or we build in-house solution
    container_name: komodo-periphery
    labels:
      komodo.skip: # Prevent Komodo from stopping with StopAllContainers
    env_file: ${ENV_FILE}
    volumes:
      ## Mount external docker socket
      - /var/run/docker.sock:/var/run/docker.sock
      ## Allow Periphery to see processes outside of container
      - /proc:/proc
      ## Specify the Periphery agent root directory.
      ## Must be the same inside and outside the container,
      ## or docker will get confused. See https://github.com/moghtech/komodo/discussions/180.
      ## Default: /etc/komodo.
      - ${PERIPHERY_ROOT_DIRECTORY:-/etc/komodo}:${PERIPHERY_ROOT_DIRECTORY:-/etc/komodo}
    networks:
      - komodo-network
    restart: unless-stopped

volumes:
  # Komodo
  komodo-keys:
  # Mongo
  mongo-data:
  mongo-config:

networks:
  komodo-network: # Needed for containers to connect to each other, as central-network is listed in one of them
  central-network:
    name: central-network
    external: true
