################################
# 🦎 KOMODO COMPOSE - MONGO 🦎 #
################################

## This compose file will deploy:
##   1. MongoDB
##   2. Komodo Core
##   3. Komodo Periphery

services:
  mongo:
    image: mongo:8@sha256:6f55a078e025aa29fea2826c82f67ff2f774b82efd816c4c30bbfe67904f0bb8
    labels:
      komodo.skip: # Prevent Komodo from stopping with StopAllContainers
    command: --quiet --wiredTigerCacheSizeGB 0.25
    # ports:
    #   - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${KOMODO_DB_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${KOMODO_DB_PASSWORD}"
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb
    networks:
      - komodo-network
    restart: unless-stopped
  
  core:
    image: ghcr.io/moghtech/komodo-core:1.19@sha256:a1cceb4f971443b1e9f2a767788f663d0afb6244ee2135f7fe3fd1036af37ade
    container_name: komodo-core
    depends_on:
      - mongo
    labels:
      komodo.skip: # Prevent Komodo from stopping with StopAllContainers
    ports:
      - "9120:9120"
    env_file: "${ENV_FILE}"
    environment:
      KOMODO_DATABASE_ADDRESS: mongo:27017
      KOMODO_DATABASE_USERNAME: "${KOMODO_DB_USERNAME}"
      KOMODO_DATABASE_PASSWORD: "${KOMODO_DB_PASSWORD}"
    volumes:
      ## Store dated backups of the database - https://komo.do/docs/setup/backup
      - ${COMPOSE_KOMODO_BACKUPS_PATH}:/backups
      ## Store sync files on server
      # - /path/to/syncs:/syncs
      ## Optionally mount a custom core.config.toml
      # - /path/to/core.config.toml:/config/config.toml
    ## Allows for systemd Periphery connection at 
    ## "https://host.docker.internal:8120"
    # extra_hosts:
    #   - host.docker.internal:host-gateway
    networks: # For connecting with other services directly
      - komodo-network
      - central-network
    restart: unless-stopped

  ## Deploy Periphery container using this block,
  ## or deploy the Periphery binary with systemd using 
  ## https://github.com/moghtech/komodo/tree/main/scripts
  periphery:
    image: ghcr.io/moghtech/komodo-periphery:1.19@sha256:bd79cf960ed054fe8e02384322303e462448679b1149dde48bbef151417255b1
    container_name: komodo-periphery
    labels:
      komodo.skip: # Prevent Komodo from stopping with StopAllContainers
    env_file: ${ENV_FILE}
    volumes:
      ## Mount external docker socket
      - /var/run/docker.sock:/var/run/docker.sock
      ## Allow Periphery to see processes outside of container
      - /proc:/proc
      ## Specify the Periphery agent root directory.
      ## Must be the same inside and outside the container,
      ## or docker will get confused. See https://github.com/moghtech/komodo/discussions/180.
      ## Default: /etc/komodo.
      - ${PERIPHERY_ROOT_DIRECTORY:-/etc/komodo}:${PERIPHERY_ROOT_DIRECTORY:-/etc/komodo}
    networks:
      - komodo-network
    restart: unless-stopped

volumes:
  # Mongo
  mongo-data:
  mongo-config:

networks:
  komodo-network: # Needed for containers to connect to each other, as central-network is listed in one of them
  central-network:
    name: central-network
    external: true
